In [1]:
def add_binary_nums(x,y):
        x=bin(x)[2:]
        y=bin(y)[2:]
        max_len = max(len(x), len(y))
        flag = False
        x = x.zfill(max_len)
        y = y.zfill(max_len)

        result = ''
        carry = 0

        for i in range(max_len-1,-1,-1):
            r = carry
            r += 1 if x[i] == '1' else 0
            r += 1 if y[i] == '1' else 0
            result = ('1' if r % 2 == 1 else '0') + result
            carry = 0 if r < 2 else 1       

        if carry !=0 : 
            flag=True
            result = '1' + result

        return flag

In [2]:
has_carry = 0
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

In [3]:
import copy
import numpy as np

In [4]:
correct = 0
int2binary = {}
binary_dim = 8

In [5]:
largest_number = pow(2,binary_dim)
binary = np.unpackbits(
    np.array([range(largest_number)],dtype=np.uint8).T,axis=1)
for i in range(largest_number):
    int2binary[i] = binary[i]

In [6]:
alpha = 0.1
input_dim = 2
hidden_dim = 16
output_dim = 1

In [7]:
Wx = 2*np.random.random((input_dim,hidden_dim)) - 1
Wy = 2*np.random.random((hidden_dim,output_dim)) - 1
Wr = 2*np.random.random((hidden_dim,hidden_dim)) - 1
Bx = 2*np.random.random((hidden_dim,1)) - 1
By = 2*np.random.random((1,1)) - 1

In [8]:
for j in range(100000):
    
    # generate a simple addition problem (a + b = c)
    a_int = np.random.randint(largest_number/2) # int version
    a = int2binary[a_int] # binary encoding

    b_int = np.random.randint(largest_number/2) # int version
    b = int2binary[b_int] # binary encoding

    # true answer
    c_int = a_int + b_int
    c = int2binary[c_int]
    
    # where we'll store our best guess (binary encoded)
    d = np.zeros_like(c)

    hts = [np.zeros((16,1))]
    yts = []
    
    for position in range(binary_dim):
        
        # generate input and output
        X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
        y = np.array([[c[binary_dim - position - 1]]]).T
        
        ht = sigmoid(np.dot(X,Wx) + np.dot(hts[-1],Wr) + Bx)
        

ValueError: shapes (16,1) and (16,16) not aligned: 1 (dim 1) != 16 (dim 0)

In [9]:
a_int = np.random.randint(largest_number/2) # int version
a = int2binary[a_int] # binary encoding

b_int = np.random.randint(largest_number/2) # int version
b = int2binary[b_int] # binary encoding

# true answer
c_int = a_int + b_int
c = int2binary[c_int]

# where we'll store our best guess (binary encoded)
d = np.zeros_like(c)

hts = [np.zeros((16,1))]
yts = []

for position in range(binary_dim):

    # generate input and output
    X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
    y = np.array([[c[binary_dim - position - 1]]]).T
    #forward prop
    ht = sigmoid(np.matmul(X,Wx) + np.matmul(hts[-1].T,Wr) + Bx.T)
    yt = sigmoid(np.matmul(ht,Wy)+By)
    ht = ht.T
    
    dyt = 2*(yt-y)
    dzt = dyt*yt*(1-yt)
    dWy = dzt*ht
    dBy = copy.deepcopy(dzt)
    dht = dzt*Wy
    dvt = dht * ht * (1-ht)
    dWx = np.matmul(X.T,dvt.T)
    dBx = copy.deepcopy(dvt)
    dWr = np.matmul(dvt, ht.T)
    
    
    hts.append(ht)
    yts.append(yt)

In [10]:
a = np.array([1,2,3,4])
b = np.array([a for i in range(4)])

np.dot(a,b)

array([10, 20, 30, 40])

In [11]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [26]:
import copy, numpy as np
np.random.seed(0)

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_derivative(output):
    return output*(1-output)

correct = 0
has_carry = 0
# training dataset generation
int2binary = {}
binary_dim = 8

largest_number = pow(2,binary_dim)
binary = np.unpackbits(
    np.array([range(largest_number)],dtype=np.uint8).T,axis=1)
for i in range(largest_number):
    int2binary[i] = binary[i]


# input variables
alpha = 1
input_dim = 2
hidden_dim = 16
output_dim = 1

Wx = 2*np.random.random((input_dim,hidden_dim)) - 1
Wy = 2*np.random.random((hidden_dim,output_dim)) - 1
Wr = 2*np.random.random((hidden_dim,hidden_dim)) - 1

Wx_update = np.zeros_like(Wx)
Wy_update = np.zeros_like(Wy)
Wr_update = np.zeros_like(Wr)

# training logic
for j in range(30000):
    np.random.seed(2)
    # generate a simple addition problem (a + b = c)
    a_int = np.random.randint(largest_number/2) # int version
    a = int2binary[a_int] # binary encoding

    b_int = np.random.randint(largest_number/2) # int version
    b = int2binary[b_int] # binary encoding

    # true answer
    c_int = a_int + b_int
    c = int2binary[c_int]
    
    # where we'll store our best guess (binary encoded)
    pred = np.zeros_like(c)

    overallError = 0
    
    dyts = list()
    hts = list()
    hts.append(np.zeros(hidden_dim))
    
    # moving along the positions in the binary encoding
    for position in range(binary_dim):
        
        # generate input and output
        X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
        y = np.array([[c[binary_dim - position - 1]]]).T

        # hidden layer (input ~+ prev_hidden)
        ht = sigmoid(np.dot(X,Wx) + np.dot(hts[-1],Wr))

        # output layer (new binary representation)
        yt = sigmoid(np.dot(ht,Wy))

        # did we miss?... if so, by how much?
        yt_error = y - yt
        dyts.append((yt_error)*sigmoid_derivative(yt))
        overallError += np.abs(yt_error[0])
    
        # decode estimate so we can print it out
        pred[binary_dim - position - 1] = np.round(yt[0][0])
        
        # store hidden layer so we can use it in the next timestep
        hts.append(copy.deepcopy(ht))
    
    future_dht = np.zeros(hidden_dim)
    
    for position in range(binary_dim):
        
        X = np.array([[a[position],b[position]]])
        ht = hts[-position-1]
        prev_ht = hts[-position-2]
        
        # error at output layer
        dyt = dyts[-position-1]
        # error at hidden layer
        dht = (future_dht.dot(Wr.T) + dyt.dot(Wy.T)) * sigmoid_derivative(ht)

        # let's update all our weights so we can try again
        Wy_update += np.atleast_2d(ht).T.dot(dyt)
        Wr_update += np.atleast_2d(prev_ht).T.dot(dht)
        Wx_update += X.T.dot(dht)
        
        future_dht = dht
    

    Wx += Wx_update * alpha
    Wy += Wy_update * alpha
    Wr += Wr_update * alpha    

    Wx_update *= 0
    Wy_update *= 0
    Wr_update *= 0
    
    if np.array_equal(pred.T,c):
        correct+=1
    else:
        if add_binary_nums(a_int,b_int):
            has_carry+=1

In [29]:
correct/30000

0.9978666666666667

In [30]:
has_carry

0

In [165]:
has_carry

6624

In [166]:
 100000 - correct

99972

In [111]:
correct

0

In [17]:
np.shape(dvt)

(16, 1)

In [113]:
c

array([0, 1, 0, 1, 0, 1, 1, 0], dtype=uint8)

In [116]:
hts

[array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]), array([[0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5],
        [0.5]]), array([[4.86589219e-014],
        [5.05718173e-103],
        [4.83333170e-026],
        [1.86278440e-002],
        [1.45276085e-058],
        [2.84869319e-082],
        [1.59283494e-017],
        [1.00724998e-069],
        [5.15986842e-013],
        [1.00000000e+000],
        [9.98425328e-001],
        [4.82698686e-041],
        [1.12751165e-023],
        [1.53186513e-009],
        [4.01697030e-033],
        [9.72220663e-001]]), array([[5.14287000e-33],
        [1.05315102e-26],
        [3.85227305e-31],
        [1.27351533e-12

In [117]:
len(hts)

9