In [1]:
def add_binary_nums(x,y):
        x=bin(x)[2:]
        y=bin(y)[2:]
        max_len = max(len(x), len(y))
        flag = False
        x = x.zfill(max_len)
        y = y.zfill(max_len)

        result = ''
        carry = 0

        for i in range(max_len-1,-1,-1):
            r = carry
            r += 1 if x[i] == '1' else 0
            r += 1 if y[i] == '1' else 0
            result = ('1' if r % 2 == 1 else '0') + result
            carry = 0 if r < 2 else 1       

        if carry !=0 : 
            flag=True
            result = '1' + result

        return flag

In [2]:
has_carry = 0
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

In [3]:
import copy
import numpy as np

In [4]:
correct = 0
int2binary = {}
binary_dim = 8

In [5]:
largest_number = pow(2,binary_dim)
binary = np.unpackbits(
    np.array([range(largest_number)],dtype=np.uint8).T,axis=1)
for i in range(largest_number):
    int2binary[i] = binary[i]

In [6]:
alpha = 0.1
input_dim = 2
hidden_dim = 16
output_dim = 1

In [7]:
Wx = 2*np.random.random((input_dim,hidden_dim)) - 1
Wy = 2*np.random.random((hidden_dim,output_dim)) - 1
Wr = 2*np.random.random((hidden_dim,hidden_dim)) - 1
Bx = 2*np.random.random((hidden_dim,1)) - 1
By = 2*np.random.random((1,1)) - 1

In [8]:
for j in range(100000):
    
    # generate a simple addition problem (a + b = c)
    a_int = np.random.randint(largest_number/2) # int version
    a = int2binary[a_int] # binary encoding

    b_int = np.random.randint(largest_number/2) # int version
    b = int2binary[b_int] # binary encoding

    # true answer
    c_int = a_int + b_int
    c = int2binary[c_int]
    
    # where we'll store our best guess (binary encoded)
    d = np.zeros_like(c)

    hts = [np.zeros((16,1))]
    yts = []
    
    for position in range(binary_dim):
        
        # generate input and output
        X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
        y = np.array([[c[binary_dim - position - 1]]]).T
        
        ht = sigmoid(np.dot(X,Wx) + np.dot(hts[-1],Wr) + Bx)
        

ValueError: shapes (16,1) and (16,16) not aligned: 1 (dim 1) != 16 (dim 0)

In [9]:
a_int = np.random.randint(largest_number/2) # int version
a = int2binary[a_int] # binary encoding

b_int = np.random.randint(largest_number/2) # int version
b = int2binary[b_int] # binary encoding

# true answer
c_int = a_int + b_int
c = int2binary[c_int]

# where we'll store our best guess (binary encoded)
d = np.zeros_like(c)

hts = [np.zeros((16,1))]
yts = []

for position in range(binary_dim):

    # generate input and output
    X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
    y = np.array([[c[binary_dim - position - 1]]]).T
    #forward prop
    ht = sigmoid(np.matmul(X,Wx) + np.matmul(hts[-1].T,Wr) + Bx.T)
    yt = sigmoid(np.matmul(ht,Wy)+By)
    ht = ht.T
    
    dyt = 2*(yt-y)
    dzt = dyt*yt*(1-yt)
    dWy = dzt*ht
    dBy = copy.deepcopy(dzt)
    dht = dzt*Wy
    dvt = dht * ht * (1-ht)
    dWx = np.matmul(X.T,dvt.T)
    dBx = copy.deepcopy(dvt)
    dWr = np.matmul(dvt, ht.T)
    
    
    hts.append(ht)
    yts.append(yt)

In [10]:
a = np.array([1,2,3,4])
b = np.array([a for i in range(4)])

np.dot(a,b)

array([10, 20, 30, 40])

In [11]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
import copy, numpy as np
np.random.seed(0)

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_derivative(output):
    return output*(1-output)

correct = 0
has_carry = 0
# training dataset generation
int2binary = {}
binary_dim = 8

largest_number = pow(2,binary_dim)
binary = np.unpackbits(
    np.array([range(largest_number)],dtype=np.uint8).T,axis=1)
for i in range(largest_number):
    int2binary[i] = binary[i]


# input variables
alpha = 1
input_dim = 2
hidden_dim = 16
output_dim = 1

Wx = 2*np.random.random((input_dim,hidden_dim)) - 1
Wy = 2*np.random.random((hidden_dim,output_dim)) - 1
Wr = 2*np.random.random((hidden_dim,hidden_dim)) - 1

Wx_update = np.zeros_like(Wx)
Wy_update = np.zeros_like(Wy)
Wr_update = np.zeros_like(Wr)

# training logic
for j in range(75000):
    np.random.seed(2)
    # generate a simple addition problem (a + b = c)
    a_int = np.random.randint(largest_number/2) # int version
    a = int2binary[a_int] # binary encoding

    b_int = np.random.randint(largest_number/2) # int version
    b = int2binary[b_int] # binary encoding

    # true answer
    c_int = a_int + b_int
    c = int2binary[c_int]
    
    # where we'll store our best guess (binary encoded)
    pred = np.zeros_like(c)

    overallError = 0
    
    dyts = list()
    hts = list()
    hts.append(np.zeros(hidden_dim))
    
    # moving along the positions in the binary encoding
    for position in range(binary_dim):
        
        # generate input and output
        X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
        y = np.array([[c[binary_dim - position - 1]]]).T

        # hidden layer (input ~+ prev_hidden)
        ht = sigmoid(np.dot(X,Wx) + np.dot(hts[-1],Wr))

        # output layer (new binary representation)
        yt = sigmoid(np.dot(ht,Wy))

        # did we miss?... if so, by how much?
        yt_error = y - yt
        dyts.append((yt_error)*sigmoid_derivative(yt))
        overallError += np.abs(yt_error[0])
    
        # decode estimate so we can print it out
        pred[binary_dim - position - 1] = np.round(yt[0][0])
        
        # store hidden layer so we can use it in the next timestep
        hts.append(copy.deepcopy(ht))
    
    future_dht = np.zeros(hidden_dim)
    
    for position in range(binary_dim):
        
        X = np.array([[a[position],b[position]]])
        ht = hts[-position-1]
        prev_ht = hts[-position-2]
        
        # error at output layer
        dyt = dyts[-position-1]
        # error at hidden layer
        dht = (future_dht.dot(Wr.T) + dyt.dot(Wy.T)) * sigmoid_derivative(ht)

        # let's update all our weights so we can try again
        Wy_update += np.atleast_2d(ht).T.dot(dyt)
        Wr_update += np.atleast_2d(prev_ht).T.dot(dht)
        Wx_update += X.T.dot(dht)
        
        future_dht = dht
    

    Wx += Wx_update * alpha
    Wy += Wy_update * alpha
    Wr += Wr_update * alpha    

    Wx_update *= 0
    Wy_update *= 0
    Wr_update *= 0
    
    if np.array_equal(pred.T,c):
        correct+=1
    else:
        if add_binary_nums(a_int,b_int):
            has_carry+=1

In [13]:
correct/75000

0.9991466666666666

In [14]:
has_carry

0

In [15]:
has_carry

0

In [16]:
dWr

array([[ 0.01626199,  0.02637438,  0.04063752,  0.02286483,  0.00862342,
         0.01498595,  0.00929334,  0.03802824,  0.03633591,  0.01030256,
         0.00857362,  0.02734708,  0.02516166,  0.01656837,  0.0167132 ,
         0.01580723],
       [ 0.00042742,  0.0006932 ,  0.00106808,  0.00060096,  0.00022665,
         0.00039388,  0.00024426,  0.0009995 ,  0.00095502,  0.00027078,
         0.00022534,  0.00071877,  0.00066133,  0.00043547,  0.00043928,
         0.00041546],
       [-0.00616432, -0.00999755, -0.01540417, -0.00866721, -0.00326882,
        -0.00568062, -0.00352276, -0.01441509, -0.01377359, -0.00390532,
        -0.00324994, -0.01036626, -0.00953785, -0.00628045, -0.00633535,
        -0.00599193],
       [ 0.0194811 ,  0.03159527,  0.04868183,  0.02739099,  0.01033045,
         0.01795246,  0.01113298,  0.04555603,  0.04352871,  0.01234198,
         0.01027079,  0.03276051,  0.03014248,  0.01984813,  0.02002162,
         0.01893631],
       [ 0.01319127,  0.02139415,  0

In [37]:
correct

74936

In [38]:
np.shape(dvt)

(16, 1)

In [39]:
c

array([0, 0, 1, 1, 0, 1, 1, 1], dtype=uint8)

In [40]:
hts

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[0.22319218, 0.73563206, 0.38335928, 0.78573162, 0.84878664,
         0.63998958, 0.55215944, 0.67863053, 0.14037539, 0.25566723,
         0.16543481, 0.73471146, 0.59180901, 0.19258906, 0.37978856,
         0.77002291]]),
 array([[0.43304557, 0.17410651, 0.68749324, 0.07774118, 0.98694741,
         0.29324448, 0.92776091, 0.70748902, 0.07520501, 0.55230009,
         0.81262783, 0.35410581, 0.88874736, 0.80827536, 0.21791857,
         0.13497929]]),
 array([[0.92168186, 0.73446371, 0.57708055, 0.13158051, 0.80438323,
         0.21481745, 0.06225238, 0.88031929, 0.10915868, 0.89455957,
         0.17813619, 0.90897291, 0.50055165, 0.88242902, 0.47677208,
         0.0648561 ]]),
 array([[0.04093638, 0.87199491, 0.91904017, 0.05218522, 0.92664667,
         0.07611035, 0.04942959, 0.546895  , 0.94819746, 0.07527593,
         0.04977585, 0.24380241, 0.05656054, 0.03231832, 0.68911976,
         0.06573708]]),
 a

In [41]:
len(hts)

9

In [43]:
pred

array([0, 0, 1, 1, 0, 1, 1, 1], dtype=uint8)